# COREDNS CONFIG FILE

# DOMAIN-BLACKLIST
template IN ANY rdl.lgtvcommon.com eic.homeprv.lgtvcommon.com ruc.homeprv.lgtvcommon.com aic.homeprv.lgtvcommon.com aic.cdpbeacon.lgtvcommon.com ad.lgsmartad.com eic.cdpbeacon.lgtvcommon.com qt2-ngfts.lge.com aic.wiseconfig.lgtvcommon.com eic.nudge.lgtvcommon.com kic.homeprv.lgtvcommon.com ruc.nudge.lgtvcommon.com aic.nudge.lgtvcommon.com kic.nudge.lgtvcommon.com {

	rcode NXDOMAIN
	authority "{{ .Zone }} 3600 IN SOA {{ .Name }}{{ .Class }}.{{ .Type }}. blocked.nxdomain. (1 60 60 60 60)"
}
