### DNSMASQ CONFIG
### WhiteListed Domains ###
server=/raw.githubusercontent.com/#	# Source
### BlackListed Domains ###
server=/qt2-ngfts.lge.com/	# NATIVE-LGWEBOS
server=/ad.lgsmartad.com/	# NATIVE-LGWEBOS
server=/aic.cdpbeacon.lgtvcommon.com/	# NATIVE-LGWEBOS
server=/eic.cdpbeacon.lgtvcommon.com/	# NATIVE-LGWEBOS
server=/aic.homeprv.lgtvcommon.com/	# NATIVE-LGWEBOS
server=/eic.homeprv.lgtvcommon.com/	# NATIVE-LGWEBOS
server=/kic.homeprv.lgtvcommon.com/	# NATIVE-LGWEBOS
server=/ruc.homeprv.lgtvcommon.com/	# NATIVE-LGWEBOS
server=/aic.nudge.lgtvcommon.com/	# NATIVE-LGWEBOS
server=/eic.nudge.lgtvcommon.com/	# NATIVE-LGWEBOS
server=/kic.nudge.lgtvcommon.com/	# NATIVE-LGWEBOS
server=/ruc.nudge.lgtvcommon.com/	# NATIVE-LGWEBOS
server=/rdl.lgtvcommon.com/	# NATIVE-LGWEBOS
server=/aic.wiseconfig.lgtvcommon.com/	# NATIVE-LGWEBOS
### EOF ###