-- Whitelisted Domains
daf.add 'qname = raw.githubusercontent.com pass'	 -- Source
-- BlackListed Domains
daf.add 'qname = qt2-ngfts.lge.com deny'	 -- NATIVE-LGWEBOS
daf.add 'qname = ad.lgsmartad.com deny'	 -- NATIVE-LGWEBOS
daf.add 'qname = aic.cdpbeacon.lgtvcommon.com deny'	 -- NATIVE-LGWEBOS
daf.add 'qname = eic.cdpbeacon.lgtvcommon.com deny'	 -- NATIVE-LGWEBOS
daf.add 'qname = aic.homeprv.lgtvcommon.com deny'	 -- NATIVE-LGWEBOS
daf.add 'qname = eic.homeprv.lgtvcommon.com deny'	 -- NATIVE-LGWEBOS
daf.add 'qname = kic.homeprv.lgtvcommon.com deny'	 -- NATIVE-LGWEBOS
daf.add 'qname = ruc.homeprv.lgtvcommon.com deny'	 -- NATIVE-LGWEBOS
daf.add 'qname = aic.nudge.lgtvcommon.com deny'	 -- NATIVE-LGWEBOS
daf.add 'qname = eic.nudge.lgtvcommon.com deny'	 -- NATIVE-LGWEBOS
daf.add 'qname = kic.nudge.lgtvcommon.com deny'	 -- NATIVE-LGWEBOS
daf.add 'qname = ruc.nudge.lgtvcommon.com deny'	 -- NATIVE-LGWEBOS
daf.add 'qname = rdl.lgtvcommon.com deny'	 -- NATIVE-LGWEBOS
daf.add 'qname = aic.wiseconfig.lgtvcommon.com deny'	 -- NATIVE-LGWEBOS
daf.add 'qname = alphonso.tv deny'	 -- NATIVE-LGWEBOS
-- EOF