server:

	### BlackListed Domains ###
	local-zone: "qt2-ngfts.lge.com" always_nxdomain	# NATIVE-LGWEBOS
	local-zone: "ad.lgsmartad.com" always_nxdomain	# NATIVE-LGWEBOS
	local-zone: "aic.cdpbeacon.lgtvcommon.com" always_nxdomain	# NATIVE-LGWEBOS
	local-zone: "eic.cdpbeacon.lgtvcommon.com" always_nxdomain	# NATIVE-LGWEBOS
	local-zone: "aic.homeprv.lgtvcommon.com" always_nxdomain	# NATIVE-LGWEBOS
	local-zone: "eic.homeprv.lgtvcommon.com" always_nxdomain	# NATIVE-LGWEBOS
	local-zone: "kic.homeprv.lgtvcommon.com" always_nxdomain	# NATIVE-LGWEBOS
	local-zone: "ruc.homeprv.lgtvcommon.com" always_nxdomain	# NATIVE-LGWEBOS
	local-zone: "aic.nudge.lgtvcommon.com" always_nxdomain	# NATIVE-LGWEBOS
	local-zone: "eic.nudge.lgtvcommon.com" always_nxdomain	# NATIVE-LGWEBOS
	local-zone: "kic.nudge.lgtvcommon.com" always_nxdomain	# NATIVE-LGWEBOS
	local-zone: "ruc.nudge.lgtvcommon.com" always_nxdomain	# NATIVE-LGWEBOS
	local-zone: "rdl.lgtvcommon.com" always_nxdomain	# NATIVE-LGWEBOS
	local-zone: "aic.wiseconfig.lgtvcommon.com" always_nxdomain	# NATIVE-LGWEBOS
	local-zone: "alphonso.tv" always_nxdomain	# NATIVE-LGWEBOS

### EOF ###